### ISSUE TITLE
 Experiment environment

### ISSUE THREAD

**Issue by xilinx88** [GGGHSL/InfoSwap-master#11]
hi. I'm implementing training code of this paper.  Can you tell me about details of the training environment? (batch size,  gpu ...)

**Comment by lyx0208** [comment]
> 
I think batch size is 4 according to the supplementary

**Comment by akafen** [comment]
> > 
> 
> I think batch size is 4 according to the supplementary

Where I can get the Supplementary

**Comment by GGGHSL** [comment]
@lyx0208 Yes, that's correct, in addition, InfoSwap-512 is trained on 2 RTX 3090 GPUs, with a batch size of 2 on each GPU. You may find more training details from the supplementary material @xilinx88 :)
