### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints_512/w_kernel_smooth\\ckpt_ks_G.pth'

### ISSUE THREAD

**Issue by an-zi-li** [GGGHSL/InfoSwap-master#13]
Hello, I have the following problem now. Could you please provide me with this checkpoint? Thank you

FileNotFoundError:No such file or directory: './checkpoints_512/w_kernel_smooth\\ckpt_ks_G.pth'

**Comment by lyx0208** [comment]
You can refer to the USAGE.md and send the email.
