### ISSUE TITLE
An inconsistency of the input of IBLayer

### ISSUE THREAD

**Issue by lyx0208** [GGGHSL/InfoSwap-master#15]
In inference_demo.py, R = encoder.features[i]; while in the forward function of IIB, R = readout_feats[i].
Which should I use for training?
And when I use R = readout_feats[i], Info is really large (5668875) at the beginning of training.

**Comment by lyx0208** [comment]
solved

**Comment by lyx0208** [comment]
solved

**Comment by an-zi-li** [comment]
Excuse me, do you have a training code？
