### ISSUE TITLE
There was a error saving the picture

### ISSUE THREAD

**Issue by an-zi-li** [GGGHSL/InfoSwap-master#17]
When I ran inference_demo.py as a test, I had the following problems while saving images:
![bug1](https://user-images.githubusercontent.com/95530998/171976811-5afb176a-60d3-449f-9b1b-72567a327352.png)

**Comment by ygtxr1997** [comment]
Line 90, change to:
```python
save_path = os.path.join(str(save_dir), str(prefix) + '_gen.' + str(suffix))
```

**Comment by GGGHSL** [comment]
Thank you @ygtxr1997
