### ISSUE TITLE
Awaiting email response.

### ISSUE THREAD

**Issue by ykk648** [GGGHSL/InfoSwap-master#3]
Sent an email a few days ago and haven't received a reply yet.

**Comment by GGGHSL** [comment]
According to the rules of our institute (CASIA), we cannot provide pre-trained models to commercial organizations. 

Taking into account all relevant legal and ethical challenges, non-commercial research organizations applying for the models must first provide a description of their intended use and sign an agreement not to use our model/code for commercial, illegal, harmful, or unethical purposes before being granted access.

**Comment by molo32** [comment]
how long does it take to answer the email?

I want the models to test the quality of the face swap.
I will not use your model/code for commercial, illegal, harmful or unethical purposes

**Comment by ykk648** [comment]
@molo32  Inf ∞
